services:
  - type: web
    name: online-merchant
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput --clear
    startCommand: python scripts/startup.py
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*.onrender.com"
      - key: PYTHONUNBUFFERED
        value: "1"
