services:
  - type: web
    name: online-merchant
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn config.wsgi --log-file -
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: online_merchant-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: "*.onrender.com"
        sync: false

databases:
  - name: online_merchant-db
    databaseName: online_merchant_db
    user: online_merchant_db_user
