# Generated by Devin

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='bidder_increment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preferred bid increment for auto-bidding', max_digits=10, null=True),
        ),
    ]
